FROM openjdk:8-jdk-alpine

RUN apk --update add git unzip wget apache-ant maven curl bash openjdk8-jre python

RUN git clone https://github.com/actnforchildren/vsaq

RUN vsaq/do.sh install_deps && vsaq/do.sh build